<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Feedback_topic extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Feedback_topic_model');
    } 

    /*
     * Listing of feedback_topics
     */
    function index()
    {
        $data['feedback_topics'] = $this->Feedback_topic_model->get_all_feedback_topics();
        
        $data['_view'] = 'feedback_topic/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new feedback_topic
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'lecture_id' => $this->input->post('lecture_id'),
				'topic_id' => $this->input->post('topic_id'),
				'rating' => $this->input->post('rating'),
				'timestamp' => $this->input->post('timestamp'),
            );
            
            $feedback_topic_id = $this->Feedback_topic_model->add_feedback_topic($params);
            redirect('feedback_topic/index');
        }
        else
        {            
            $data['_view'] = 'feedback_topic/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a feedback_topic
     */
    function edit($feedback_topic_id)
    {   
        // check if the feedback_topic exists before trying to edit it
        $data['feedback_topic'] = $this->Feedback_topic_model->get_feedback_topic($feedback_topic_id);
        
        if(isset($data['feedback_topic']['feedback_topic_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'lecture_id' => $this->input->post('lecture_id'),
					'topic_id' => $this->input->post('topic_id'),
					'rating' => $this->input->post('rating'),
					'timestamp' => $this->input->post('timestamp'),
                );

                $this->Feedback_topic_model->update_feedback_topic($feedback_topic_id,$params);            
                redirect('feedback_topic/index');
            }
            else
            {
                $data['_view'] = 'feedback_topic/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The feedback_topic you are trying to edit does not exist.');
    } 

    /*
     * Deleting feedback_topic
     */
    function remove($feedback_topic_id)
    {
        $feedback_topic = $this->Feedback_topic_model->get_feedback_topic($feedback_topic_id);

        // check if the feedback_topic exists before trying to delete it
        if(isset($feedback_topic['feedback_topic_id']))
        {
            $this->Feedback_topic_model->delete_feedback_topic($feedback_topic_id);
            redirect('feedback_topic/index');
        }
        else
            show_error('The feedback_topic you are trying to delete does not exist.');
    }
    
}
