<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Feedback extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Feedback_model');
    } 

    /*
     * Listing of feedback
     */
    function index()
    {
        $data['feedback'] = $this->Feedback_model->get_all_feedback();
        
        $data['_view'] = 'feedback/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new feedback
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'lecture_id' => $this->input->post('lecture_id'),
				'student_id' => $this->input->post('student_id'),
				'experience' => $this->input->post('experience'),
				'timestamp' => $this->input->post('timestamp'),
				'improvements' => $this->input->post('improvements'),
				'teacher_feedback' => $this->input->post('teacher_feedback'),
            );
            
            $feedback_id = $this->Feedback_model->add_feedback($params);
            redirect('feedback/index');
        }
        else
        {            
            $data['_view'] = 'feedback/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a feedback
     */
    function edit($feedback_id)
    {   
        // check if the feedback exists before trying to edit it
        $data['feedback'] = $this->Feedback_model->get_feedback($feedback_id);
        
        if(isset($data['feedback']['feedback_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'lecture_id' => $this->input->post('lecture_id'),
					'student_id' => $this->input->post('student_id'),
					'experience' => $this->input->post('experience'),
					'timestamp' => $this->input->post('timestamp'),
					'improvements' => $this->input->post('improvements'),
					'teacher_feedback' => $this->input->post('teacher_feedback'),
                );

                $this->Feedback_model->update_feedback($feedback_id,$params);            
                redirect('feedback/index');
            }
            else
            {
                $data['_view'] = 'feedback/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The feedback you are trying to edit does not exist.');
    } 

    /*
     * Deleting feedback
     */
    function remove($feedback_id)
    {
        $feedback = $this->Feedback_model->get_feedback($feedback_id);

        // check if the feedback exists before trying to delete it
        if(isset($feedback['feedback_id']))
        {
            $this->Feedback_model->delete_feedback($feedback_id);
            redirect('feedback/index');
        }
        else
            show_error('The feedback you are trying to delete does not exist.');
    }
    
}
