<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Lecture_topic extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Lecture_topic_model');
    } 

    /*
     * Listing of lecture_topics
     */
    function index()
    {
        $data['lecture_topics'] = $this->Lecture_topic_model->get_all_lecture_topics();
        
        $data['_view'] = 'lecture_topic/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new lecture_topic
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'lecture_id' => $this->input->post('lecture_id'),
				'topic_id' => $this->input->post('topic_id'),
            );
            
            $lecture_topic_id = $this->Lecture_topic_model->add_lecture_topic($params);
            redirect('lecture_topic/index');
        }
        else
        {            
            $data['_view'] = 'lecture_topic/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a lecture_topic
     */
    function edit($lecture_topic_id)
    {   
        // check if the lecture_topic exists before trying to edit it
        $data['lecture_topic'] = $this->Lecture_topic_model->get_lecture_topic($lecture_topic_id);
        
        if(isset($data['lecture_topic']['lecture_topic_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'lecture_id' => $this->input->post('lecture_id'),
					'topic_id' => $this->input->post('topic_id'),
                );

                $this->Lecture_topic_model->update_lecture_topic($lecture_topic_id,$params);            
                redirect('lecture_topic/index');
            }
            else
            {
                $data['_view'] = 'lecture_topic/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The lecture_topic you are trying to edit does not exist.');
    } 

    /*
     * Deleting lecture_topic
     */
    function remove($lecture_topic_id)
    {
        $lecture_topic = $this->Lecture_topic_model->get_lecture_topic($lecture_topic_id);

        // check if the lecture_topic exists before trying to delete it
        if(isset($lecture_topic['lecture_topic_id']))
        {
            $this->Lecture_topic_model->delete_lecture_topic($lecture_topic_id);
            redirect('lecture_topic/index');
        }
        else
            show_error('The lecture_topic you are trying to delete does not exist.');
    }
    
}
