<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Student extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Student_model');
    } 

    /*
     * Listing of students
     */
    function index()
    {
        $data['students'] = $this->Student_model->get_all_students();
        
        $data['_view'] = 'student/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new student
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'student_name' => $this->input->post('student_name'),
				'student_roll_no' => $this->input->post('student_roll_no'),
				'student_device_no' => $this->input->post('student_device_no'),
				'student_email' => $this->input->post('student_email'),
				'group_id' => $this->input->post('group_id'),
				'timestamp' => $this->input->post('timestamp'),
            );
            
            $student_id = $this->Student_model->add_student($params);
            redirect('student/index');
        }
        else
        {            
            $data['_view'] = 'student/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a student
     */
    function edit($student_id)
    {   
        // check if the student exists before trying to edit it
        $data['student'] = $this->Student_model->get_student($student_id);
        
        if(isset($data['student']['student_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'student_name' => $this->input->post('student_name'),
					'student_roll_no' => $this->input->post('student_roll_no'),
					'student_device_no' => $this->input->post('student_device_no'),
					'student_email' => $this->input->post('student_email'),
					'group_id' => $this->input->post('group_id'),
					'timestamp' => $this->input->post('timestamp'),
                );

                $this->Student_model->update_student($student_id,$params);            
                redirect('student/index');
            }
            else
            {
                $data['_view'] = 'student/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The student you are trying to edit does not exist.');
    } 

    /*
     * Deleting student
     */
    function remove($student_id)
    {
        $student = $this->Student_model->get_student($student_id);

        // check if the student exists before trying to delete it
        if(isset($student['student_id']))
        {
            $this->Student_model->delete_student($student_id);
            redirect('student/index');
        }
        else
            show_error('The student you are trying to delete does not exist.');
    }
    
}
