<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Teacher extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Teacher_model');
    } 

    /*
     * Listing of teachers
     */
    function index()
    {
        $data['teachers'] = $this->Teacher_model->get_all_teachers();
        
        $data['_view'] = 'teacher/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new teacher
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'teacher_name' => $this->input->post('teacher_name'),
				'teacher_email' => $this->input->post('teacher_email'),
				'teacher_phone' => $this->input->post('teacher_phone'),
				'teacher_device_id' => $this->input->post('teacher_device_id'),
            );
            
            $teacher_id = $this->Teacher_model->add_teacher($params);
            redirect('teacher/index');
        }
        else
        {            
            $data['_view'] = 'teacher/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a teacher
     */
    function edit($teacher_id)
    {   
        // check if the teacher exists before trying to edit it
        $data['teacher'] = $this->Teacher_model->get_teacher($teacher_id);
        
        if(isset($data['teacher']['teacher_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'teacher_name' => $this->input->post('teacher_name'),
					'teacher_email' => $this->input->post('teacher_email'),
					'teacher_phone' => $this->input->post('teacher_phone'),
					'teacher_device_id' => $this->input->post('teacher_device_id'),
                );

                $this->Teacher_model->update_teacher($teacher_id,$params);            
                redirect('teacher/index');
            }
            else
            {
                $data['_view'] = 'teacher/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The teacher you are trying to edit does not exist.');
    } 

    /*
     * Deleting teacher
     */
    function remove($teacher_id)
    {
        $teacher = $this->Teacher_model->get_teacher($teacher_id);

        // check if the teacher exists before trying to delete it
        if(isset($teacher['teacher_id']))
        {
            $this->Teacher_model->delete_teacher($teacher_id);
            redirect('teacher/index');
        }
        else
            show_error('The teacher you are trying to delete does not exist.');
    }
    
}
