<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Topic extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Topic_model');
    } 

    /*
     * Listing of topics
     */
    function index()
    {
        $data['topics'] = $this->Topic_model->get_all_topics();
        
        $data['_view'] = 'topic/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new topic
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'topic_name' => $this->input->post('topic_name'),
				'course_id' => $this->input->post('course_id'),
				'timestamp' => $this->input->post('timestamp'),
            );
            
            $topic_id = $this->Topic_model->add_topic($params);
            redirect('topic/index');
        }
        else
        {            
            $data['_view'] = 'topic/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a topic
     */
    function edit($topic_id)
    {   
        // check if the topic exists before trying to edit it
        $data['topic'] = $this->Topic_model->get_topic($topic_id);
        
        if(isset($data['topic']['topic_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'topic_name' => $this->input->post('topic_name'),
					'course_id' => $this->input->post('course_id'),
					'timestamp' => $this->input->post('timestamp'),
                );

                $this->Topic_model->update_topic($topic_id,$params);            
                redirect('topic/index');
            }
            else
            {
                $data['_view'] = 'topic/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The topic you are trying to edit does not exist.');
    } 

    /*
     * Deleting topic
     */
    function remove($topic_id)
    {
        $topic = $this->Topic_model->get_topic($topic_id);

        // check if the topic exists before trying to delete it
        if(isset($topic['topic_id']))
        {
            $this->Topic_model->delete_topic($topic_id);
            redirect('topic/index');
        }
        else
            show_error('The topic you are trying to delete does not exist.');
    }
    
}
