<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Attendance_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get attendance by attendance_id
     */
    function get_attendance($attendance_id)
    {
        return $this->db->get_where('attendance',array('attendance_id'=>$attendance_id))->row_array();
    }
        
    /*
     * Get all attendance
     */
    function get_all_attendance()
    {
        $this->db->order_by('attendance_id', 'desc');
        return $this->db->get('attendance')->result_array();
    }
        
    /*
     * function to add new attendance
     */
    function add_attendance($params)
    {
        $this->db->insert('attendance',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update attendance
     */
    function update_attendance($attendance_id,$params)
    {
        $this->db->where('attendance_id',$attendance_id);
        return $this->db->update('attendance',$params);
    }
    
    /*
     * function to delete attendance
     */
    function delete_attendance($attendance_id)
    {
        return $this->db->delete('attendance',array('attendance_id'=>$attendance_id));
    }
}
