<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Classroom_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get classroom by classroom_id
     */
    function get_classroom($classroom_id)
    {
        return $this->db->get_where('classroom',array('classroom_id'=>$classroom_id))->row_array();
    }
        
    /*
     * Get all classroom
     */
    function get_all_classroom()
    {
        $this->db->order_by('classroom_id', 'desc');
        return $this->db->get('classroom')->result_array();
    }
        
    /*
     * function to add new classroom
     */
    function add_classroom($params)
    {
        $this->db->insert('classroom',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update classroom
     */
    function update_classroom($classroom_id,$params)
    {
        $this->db->where('classroom_id',$classroom_id);
        return $this->db->update('classroom',$params);
    }
    
    /*
     * function to delete classroom
     */
    function delete_classroom($classroom_id)
    {
        return $this->db->delete('classroom',array('classroom_id'=>$classroom_id));
    }
}
