<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Course_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get course by course_id
     */
    function get_course($course_id)
    {
        return $this->db->get_where('courses',array('course_id'=>$course_id))->row_array();
    }
        
    /*
     * Get all courses
     */
    function get_all_courses()
    {
        $this->db->order_by('course_id', 'desc');
        return $this->db->get('courses')->result_array();
    }
        
    /*
     * function to add new course
     */
    function add_course($params)
    {
        $this->db->insert('courses',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update course
     */
    function update_course($course_id,$params)
    {
        $this->db->where('course_id',$course_id);
        return $this->db->update('courses',$params);
    }
    
    /*
     * function to delete course
     */
    function delete_course($course_id)
    {
        return $this->db->delete('courses',array('course_id'=>$course_id));
    }
}
