<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Lecture_topic_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get lecture_topic by lecture_topic_id
     */
    function get_lecture_topic($lecture_topic_id)
    {
        return $this->db->get_where('lecture_topics',array('lecture_topic_id'=>$lecture_topic_id))->row_array();
    }
        
    /*
     * Get all lecture_topics
     */
    function get_all_lecture_topics()
    {
        $this->db->order_by('lecture_topic_id', 'desc');
        return $this->db->get('lecture_topics')->result_array();
    }
        
    /*
     * function to add new lecture_topic
     */
    function add_lecture_topic($params)
    {
        $this->db->insert('lecture_topics',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update lecture_topic
     */
    function update_lecture_topic($lecture_topic_id,$params)
    {
        $this->db->where('lecture_topic_id',$lecture_topic_id);
        return $this->db->update('lecture_topics',$params);
    }
    
    /*
     * function to delete lecture_topic
     */
    function delete_lecture_topic($lecture_topic_id)
    {
        return $this->db->delete('lecture_topics',array('lecture_topic_id'=>$lecture_topic_id));
    }
}
